/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cheetah_test_Hello */

#ifndef _Included_com_cheetah_test_Hello
#define _Included_com_cheetah_test_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cheetah_test_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cheetah_test_Hello_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_cheetah_test_Hello
 * Method:    callbackHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cheetah_test_Hello_callbackHello
  (JNIEnv *, jobject);

/*
 * Class:     com_cheetah_test_Hello
 * Method:    execute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cheetah_test_Hello_execute
  (JNIEnv *, jobject);

/*
 * Class:     com_cheetah_test_Hello
 * Method:    getModel
 * Signature: (ILjava/lang/String;)Lcom/cheetah/test/JuneLeoModel;
 */
JNIEXPORT jobject JNICALL Java_com_cheetah_test_Hello_getModel
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_cheetah_test_Hello
 * Method:    getFiles
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cheetah_test_Hello_getFiles
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
